// Prayer Times for Nintendo Switch (homebrew .nro)
//
// Shows Fajr/Sunrise/Dhuhr/Asr/Maghrib/Isha for a huge built-in offline city
// database, any custom lat/lon you type in, or any place you search for by
// name online (Aladhan API). Everything about a location can be saved with
// a name for instant reuse, and the app remembers your last-used location
// and launches straight into it.
//
// Build with devkitPro (see README.md). Requires the following devkitPro
// pacman packages in addition to the base switch-dev group:
//   switch-curl switch-mbedtls switch-zlib switch-jansson
//
// Feature summary:
//   - Custom coordinates (typed in by hand)
//   - Named saved locations (custom coordinates OR searched addresses)
//   - Six calculation methods: ISNA, MWL, Umm Al-Qura, Karachi, Egyptian, Tehran
//   - Hanafi / Standard(Shafi) Asr
//   - High-latitude adjustment (Middle of Night / One-Seventh / Angle-Based)
//   - Automatic date & time from the console's own clock/timezone database
//   - Next-prayer countdown
//   - Monthly prayer timetable, scrollable, month-to-month
//   - Works fully offline; uses the live Aladhan API when available for the
//     freshest numbers, silently falling back to the offline calculator
//   - ~480 built-in offline cities, with heavy coverage of the Muslim world
//   - Type-to-filter, page jump (L/R) and letter jump (ZL/ZR) to navigate

#include <switch.h>
#include <curl/curl.h>
#include <jansson.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <strings.h>  // strcasecmp
#include <ctype.h>    // tolower
#include <sys/stat.h> // mkdir
#include <math.h>     // round
#include <time.h>     // time(), gmtime() -- used for fixed-UTC-offset locations
#include "prayer_calc.h"

// ---------------------------------------------------------------------------
// City / timezone list. See cities.h (generated by gen_cities.py). Entries
// get sorted alphabetically at startup, so ordering in that file doesn't
// matter. For anywhere not on the list, use "Search for a city" (needs
// internet) or "Enter custom coordinates" (works fully offline).
// ---------------------------------------------------------------------------
typedef struct {
    const char *label;   // shown in the menu, "City, Country"
    const char *tz;      // IANA timezone string, e.g. "Europe/London"
    double lat;
    double lon;
} CityEntry;

#include "cities.h"
static const int CITY_COUNT = sizeof(CITIES) / sizeof(CITIES[0]);

// How many rows of the city list are visible on screen at once.
#define VISIBLE_ROWS 13

// Sentinel "indices" used for the fixed rows pinned above the alphabetized
// city list. Ordered top-to-bottom as SPECIAL_ENTRIES below.
#define ENTRY_SEARCH    (-1) // search any place online by name
#define ENTRY_FILTER    (-2) // type-to-filter the offline city list
#define ENTRY_CUSTOM    (-3) // enter custom coordinates by hand
#define ENTRY_SAVED     (-4) // browse/load named saved locations
#define ENTRY_SETTINGS  (-5) // calculation method / Asr / high-latitude rule
static const int SPECIAL_ENTRIES[] = { ENTRY_SEARCH, ENTRY_FILTER, ENTRY_CUSTOM, ENTRY_SAVED, ENTRY_SETTINGS };
#define NUM_SPECIAL ((int)(sizeof(SPECIAL_ENTRIES) / sizeof(SPECIAL_ENTRIES[0])))

// ---------------------------------------------------------------------------
// Persisted settings: calculation method, Asr juristic school, and the
// high-latitude adjustment rule. Applies to both the online API call (which
// takes the equivalent parameters) and the offline calculator.
// ---------------------------------------------------------------------------
typedef struct {
    int method;       // METHOD_* from prayer_calc.h
    int asrHanafi;     // 0 = Standard/Shafi, 1 = Hanafi
    int highLatRule;   // HIGHLAT_* from prayer_calc.h
    int showAdvanced;  // 0 = simple UI (default), 1 = show timezones/method/etc
    int use24Hour;     // 1 = 24-hour clock (default), 0 = 12-hour with AM/PM
} AppSettings;

static AppSettings g_settings = { METHOD_ISNA, 0, HIGHLAT_NONE, 0, 1 };

static const int METHOD_CHOICES[] = {
    METHOD_ISNA, METHOD_MWL, METHOD_UMM_AL_QURA, METHOD_KARACHI, METHOD_EGYPTIAN, METHOD_TEHRAN, METHOD_DIYANET
};
#define NUM_METHOD_CHOICES ((int)(sizeof(METHOD_CHOICES) / sizeof(METHOD_CHOICES[0])))

static const int HIGHLAT_CHOICES[] = {
    HIGHLAT_NONE, HIGHLAT_MIDDLE_OF_NIGHT, HIGHLAT_ONE_SEVENTH, HIGHLAT_ANGLE_BASED
};
#define NUM_HIGHLAT_CHOICES ((int)(sizeof(HIGHLAT_CHOICES) / sizeof(HIGHLAT_CHOICES[0])))

static int indexOfInt(const int *arr, int n, int val) {
    for (int i = 0; i < n; i++) if (arr[i] == val) return i;
    return 0;
}

// ---------------------------------------------------------------------------
// A location: either a known IANA timezone name (accurate, DST-aware -- used
// for built-in cities and for anywhere the online search could resolve a
// timezone for), or a fixed manual UTC-offset (used for hand-typed custom
// coordinates, where we have no timezone database to look one up from
// lat/lon alone -- no DST handling in that case, which is called out in the
// UI). Used both for "the location currently on screen" and for entries in
// the saved-locations list.
// ---------------------------------------------------------------------------
typedef struct {
    char name[64];
    double lat, lon;
    int hasTz;
    char tz[64];
    double utcOffset; // used when hasTz == 0
} NamedLocation;

#define LOC_CITY   0 // a CITIES[] entry
#define LOC_NAMED  1 // a loaded/just-saved NamedLocation
#define LOC_CUSTOM 2 // one-off hand-typed coordinates, not (yet) saved
#define LOC_ADDRESS 3 // one-off free-text online search

typedef struct {
    int kind; // LOC_*
    char label[128];
    int hasTz;
    char tz[64];
    double utcOffset;
    double lat, lon;
    int hasCoords;
    char address[128]; // LOC_ADDRESS only -- re-used to refresh/refetch
} CurrentLocation;

// ---------------------------------------------------------------------------
// HTTP fetch buffer (unchanged pattern).
// ---------------------------------------------------------------------------
typedef struct {
    char *data;
    size_t size;
} HttpBuffer;

static size_t writeCallback(void *contents, size_t size, size_t nmemb, void *userp) {
    size_t realsize = size * nmemb;
    HttpBuffer *buf = (HttpBuffer *)userp;
    char *ptr = realloc(buf->data, buf->size + realsize + 1);
    if (!ptr) return 0;
    buf->data = ptr;
    memcpy(&(buf->data[buf->size]), contents, realsize);
    buf->size += realsize;
    buf->data[buf->size] = 0;
    return realsize;
}

// Result of a fetch/compute: six timing strings (HH:MM), a label, an error,
// and -- when we have it -- the coordinates/timezone behind it, so the
// result can be saved as a named location and used for the next-prayer
// countdown regardless of whether it came from the API or offline calc.
typedef struct {
    int ok;
    char error[128];
    char fajr[18];
    char sunrise[18];
    char dhuhr[18];
    char asr[18];
    char maghrib[18];
    char isha[18];
    char dateLabel[48];
    char placeLabel[128];
    int hasCoords;
    double lat, lon;
    int hasTz;
    char tz[64];
    int hasFixedOffset;
    double utcOffset;
} PrayerResult;

// Strips a trailing " (TZ)" suffix Aladhan sometimes appends to time strings.
static void cleanTime(const char *in, char *out, size_t outSize) {
    size_t i = 0;
    while (in[i] && in[i] != ' ' && i < outSize - 1) {
        out[i] = in[i];
        i++;
    }
    out[i] = 0;
}

// Parses "HH:MM" back into a fractional hour (for the countdown). Returns 0
// on a malformed string.
static int parseHourMin(const char *hm, double *outHours) {
    int h, m;
    if (sscanf(hm, "%d:%d", &h, &m) != 2) return 0;
    *outHours = h + m / 60.0;
    return 1;
}

// Parses the "data" -> "timings"/"date"/"meta" portion of an Aladhan API
// JSON response (shared by both the lat/lon and address-based lookups).
static void parseAladhanResponse(const char *jsonText, PrayerResult *result) {
    json_error_t jerr;
    json_t *root = json_loads(jsonText, 0, &jerr);

    if (!root) {
        snprintf(result->error, sizeof(result->error), "bad response (parse failed)");
        return;
    }

    json_t *data = json_object_get(root, "data");
    json_t *timings = data ? json_object_get(data, "timings") : NULL;
    json_t *dateObj = data ? json_object_get(data, "date") : NULL;
    json_t *meta = data ? json_object_get(data, "meta") : NULL;

    if (!timings) {
        json_t *dataStr = data;
        if (dataStr && json_is_string(dataStr)) {
            snprintf(result->error, sizeof(result->error), "%s", json_string_value(dataStr));
        } else {
            snprintf(result->error, sizeof(result->error), "unexpected API response");
        }
        json_decref(root);
        return;
    }

    const char *fajr = json_string_value(json_object_get(timings, "Fajr"));
    const char *sunrise = json_string_value(json_object_get(timings, "Sunrise"));
    const char *dhuhr = json_string_value(json_object_get(timings, "Dhuhr"));
    const char *asr = json_string_value(json_object_get(timings, "Asr"));
    const char *maghrib = json_string_value(json_object_get(timings, "Maghrib"));
    const char *isha = json_string_value(json_object_get(timings, "Isha"));

    if (fajr) cleanTime(fajr, result->fajr, sizeof(result->fajr));
    if (sunrise) cleanTime(sunrise, result->sunrise, sizeof(result->sunrise));
    if (dhuhr) cleanTime(dhuhr, result->dhuhr, sizeof(result->dhuhr));
    if (asr) cleanTime(asr, result->asr, sizeof(result->asr));
    if (maghrib) cleanTime(maghrib, result->maghrib, sizeof(result->maghrib));
    if (isha) cleanTime(isha, result->isha, sizeof(result->isha));

    if (dateObj) {
        json_t *readable = json_object_get(dateObj, "readable");
        if (readable && json_string_value(readable)) {
            snprintf(result->dateLabel, sizeof(result->dateLabel), "%s",
                      json_string_value(readable));
        }
    }

    // Capture coordinates/timezone if the API gave them to us, so the result
    // can be saved as a named location and used for the countdown even when
    // it came from a free-text address search.
    if (meta) {
        json_t *latJ = json_object_get(meta, "latitude");
        json_t *lonJ = json_object_get(meta, "longitude");
        json_t *tzJ = json_object_get(meta, "timezone");
        if (latJ && lonJ && (json_is_number(latJ) || json_is_real(latJ))) {
            result->lat = json_is_real(latJ) ? json_real_value(latJ) : json_number_value(latJ);
            result->lon = json_is_real(lonJ) ? json_real_value(lonJ) : json_number_value(lonJ);
            result->hasCoords = 1;
        }
        if (tzJ && json_is_string(tzJ)) {
            snprintf(result->tz, sizeof(result->tz), "%s", json_string_value(tzJ));
            result->hasTz = 1;
        }
    }

    result->ok = 1;
    json_decref(root);
}

// Appends "&method=..&school=..[&latitudeAdjustmentMethod=..]" reflecting
// the current settings, shared by both online fetch paths below.
static void appendCommonParams(char *url, size_t urlSize) {
    char extra[96];
    snprintf(extra, sizeof(extra), "&method=%d&school=%d", g_settings.method, g_settings.asrHanafi ? 1 : 0);
    strncat(url, extra, urlSize - strlen(url) - 1);
    if (g_settings.highLatRule != HIGHLAT_NONE) {
        snprintf(extra, sizeof(extra), "&latitudeAdjustmentMethod=%d", g_settings.highLatRule);
        strncat(url, extra, urlSize - strlen(url) - 1);
    }
}

// Fetch by known lat/lon (and, if known, an IANA timezone string). Used as
// the preferred (online) path, with the offline calculator as a fallback.
static void fetchPrayerTimesByCoords(const char *label, const char *tzOrNull,
                                      double lat, double lon, PrayerResult *result) {
    memset(result, 0, sizeof(PrayerResult));
    snprintf(result->placeLabel, sizeof(result->placeLabel), "%s", label);

    CURL *curl = curl_easy_init();
    if (!curl) {
        snprintf(result->error, sizeof(result->error), "curl init failed");
        return;
    }

    char url[600];
    snprintf(url, sizeof(url), "https://api.aladhan.com/v1/timings?latitude=%f&longitude=%f", lat, lon);
    if (tzOrNull && tzOrNull[0]) {
        char tzParam[96];
        snprintf(tzParam, sizeof(tzParam), "&timezonestring=%s", tzOrNull);
        strncat(url, tzParam, sizeof(url) - strlen(url) - 1);
    }
    appendCommonParams(url, sizeof(url));

    HttpBuffer buf = { .data = malloc(1), .size = 0 };

    curl_easy_setopt(curl, CURLOPT_URL, url);
    curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, writeCallback);
    curl_easy_setopt(curl, CURLOPT_WRITEDATA, (void *)&buf);
    curl_easy_setopt(curl, CURLOPT_USERAGENT, "switch-prayer-times/2.0");
    // Shorter than the Search timeout -- this path has an offline fallback,
    // so we'd rather fail fast and drop to it than make you wait 15s with
    // no signal.
    curl_easy_setopt(curl, CURLOPT_CONNECTTIMEOUT, 4L);
    curl_easy_setopt(curl, CURLOPT_TIMEOUT, 6L);
    curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1L);
    curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0L);
    curl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, 0L);

    CURLcode res = curl_easy_perform(curl);

    if (res != CURLE_OK) {
        snprintf(result->error, sizeof(result->error), "network error: %s",
                 curl_easy_strerror(res));
        curl_easy_cleanup(curl);
        free(buf.data);
        return;
    }

    parseAladhanResponse(buf.data, result);
    free(buf.data);
    curl_easy_cleanup(curl);
}

// Fetch by free-text address/place name (used for the Search option).
// Aladhan geocodes the address server-side, so this works for essentially
// any place, and its response meta tells us the coordinates/timezone it
// resolved to (captured by parseAladhanResponse), which lets a searched
// place be saved as a fully-accurate named location afterwards.
static void fetchPrayerTimesByAddress(const char *address, PrayerResult *result) {
    memset(result, 0, sizeof(PrayerResult));
    snprintf(result->placeLabel, sizeof(result->placeLabel), "%s", address);

    CURL *curl = curl_easy_init();
    if (!curl) {
        snprintf(result->error, sizeof(result->error), "curl init failed");
        return;
    }

    char *escaped = curl_easy_escape(curl, address, 0);
    if (!escaped) {
        snprintf(result->error, sizeof(result->error), "could not encode search text");
        curl_easy_cleanup(curl);
        return;
    }

    char url[800];
    snprintf(url, sizeof(url), "https://api.aladhan.com/v1/timingsByAddress?address=%s", escaped);
    curl_free(escaped);
    appendCommonParams(url, sizeof(url));

    HttpBuffer buf = { .data = malloc(1), .size = 0 };

    curl_easy_setopt(curl, CURLOPT_URL, url);
    curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, writeCallback);
    curl_easy_setopt(curl, CURLOPT_WRITEDATA, (void *)&buf);
    curl_easy_setopt(curl, CURLOPT_USERAGENT, "switch-prayer-times/2.0");
    curl_easy_setopt(curl, CURLOPT_TIMEOUT, 15L);
    curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1L);
    curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0L);
    curl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, 0L);

    CURLcode res = curl_easy_perform(curl);

    if (res != CURLE_OK) {
        snprintf(result->error, sizeof(result->error), "network error: %s",
                 curl_easy_strerror(res));
        curl_easy_cleanup(curl);
        free(buf.data);
        return;
    }

    parseAladhanResponse(buf.data, result);
    free(buf.data);
    curl_easy_cleanup(curl);
}

// Shows the system on-screen keyboard and returns what was typed (or an
// empty string if the user cancelled).
static void promptForText(const char *guideText, char *outBuf, size_t outBufSize) {
    outBuf[0] = 0;

    SwkbdConfig kbd;
    Result rc = swkbdCreate(&kbd, 0);
    if (R_FAILED(rc)) return;

    swkbdConfigMakePresetDefault(&kbd);
    swkbdConfigSetGuideText(&kbd, guideText);
    swkbdConfigSetInitialText(&kbd, "");

    rc = swkbdShow(&kbd, outBuf, outBufSize);
    swkbdClose(&kbd);

    if (R_FAILED(rc)) outBuf[0] = 0;
}

// ---------------------------------------------------------------------------
// Offline computation. For known-timezone locations, uses the console's own
// bundled IANA timezone database (the same one System Settings > Date &
// Time uses) to get an accurate local date, current time-of-day, and UTC
// offset -- DST included. For hand-typed custom coordinates (no timezone
// name available), uses the console's UTC clock plus your manually-entered
// fixed offset instead -- accurate for date/time but with no DST handling.
// ---------------------------------------------------------------------------

// Returns 1 on success and fills *year/*month/*day (local calendar date),
// *utcOffsetHours, and *nowFracHours (current local time-of-day, as a
// fractional hour -- used for the next-prayer countdown) for the given IANA
// timezone name (e.g. "Europe/Paris").
static int getLocalDateAndOffset(const char *tzName, int *year, int *month, int *day,
                                  double *utcOffsetHours, double *nowFracHours) {
    TimeZoneRule rule;
    TimeLocationName locName;
    memset(&locName, 0, sizeof(locName));
    snprintf(locName.name, sizeof(locName.name), "%s", tzName);

    Result rc = timeLoadTimeZoneRule(&locName, &rule);
    if (R_FAILED(rc)) return 0;

    u64 now = 0;
    rc = timeGetCurrentTime(TimeType_UserSystemClock, &now);
    if (R_FAILED(rc)) return 0;

    TimeCalendarTime calTime;
    TimeCalendarAdditionalInfo addInfo;
    rc = timeToCalendarTime(&rule, now, &calTime, &addInfo);
    if (R_FAILED(rc)) return 0;

    *year = calTime.year;
    *month = calTime.month;
    *day = calTime.day;
    *utcOffsetHours = addInfo.offset / 3600.0;
    if (nowFracHours) {
        *nowFracHours = calTime.hour + calTime.minute / 60.0 + calTime.second / 3600.0;
    }
    return 1;
}

// Same idea, but for a fixed manual UTC offset (custom coordinates with no
// timezone name). Always "succeeds" as far as the console clock is
// concerned -- no DST is applied, since we have no timezone rule for it.
static void getLocalDateAndOffsetFixed(double utcOffsetHours, int *year, int *month, int *day,
                                        double *nowFracHours) {
    time_t utcNow = time(NULL);
    time_t adjusted = utcNow + (time_t)llround(utcOffsetHours * 3600.0);
    struct tm tmres;
    gmtime_r(&adjusted, &tmres);
    *year = tmres.tm_year + 1900;
    *month = tmres.tm_mon + 1;
    *day = tmres.tm_mday;
    if (nowFracHours) {
        *nowFracHours = tmres.tm_hour + tmres.tm_min / 60.0 + tmres.tm_sec / 3600.0;
    }
}

// Formats a fractional-hour local time (e.g. 5.25) as "HH:MM", wrapping
// into the 0-24 range in case a calculation pushed slightly outside it.
static void formatHourMin(double hours, char *out, size_t outSize) {
    while (hours < 0.0) hours += 24.0;
    while (hours >= 24.0) hours -= 24.0;
    int h = (int)hours;
    int m = (int)round((hours - h) * 60.0);
    if (m == 60) { m = 0; h = (h + 1) % 24; }
    snprintf(out, outSize, "%02d:%02d", h, m);
}

// Re-renders an already-formatted "HH:MM" (24-hour) string for display,
// honoring the 12/24-hour setting. Always takes 24-hour input -- both the
// offline calculator and the Aladhan API give us that -- and only changes
// how it's *shown*.
static void formatTimeDisplay(const char *hhmm24, char *out, size_t outSize) {
    int h, m;
    if (sscanf(hhmm24, "%d:%d", &h, &m) != 2) {
        snprintf(out, outSize, "%s", hhmm24);
        return;
    }
    if (g_settings.use24Hour) {
        snprintf(out, outSize, "%02d:%02d", h, m);
        return;
    }
    int h12 = h % 12;
    if (h12 == 0) h12 = 12;
    snprintf(out, outSize, "%d:%02d %s", h12, m, h < 12 ? "AM" : "PM");
}

// 8-point compass label for a bearing in degrees (0 = North, clockwise).
static const char *compassDirection(double bearingDeg) {
    static const char *dirs[8] = { "N", "NE", "E", "SE", "S", "SW", "W", "NW" };
    int idx = ((int)round(bearingDeg / 45.0)) % 8;
    if (idx < 0) idx += 8;
    return dirs[idx];
}

// Computes prayer times entirely offline for a CurrentLocation, and tags the
// result with the coordinates/timezone used, so it can be saved.
static double g_lastOfflineNowFrac = 0.0; // stashed for the countdown

static void computeOfflineForLocation(const CurrentLocation *loc, PrayerResult *result) {
    memset(result, 0, sizeof(PrayerResult));
    snprintf(result->placeLabel, sizeof(result->placeLabel), "%s", loc->label);

    int year, month, day;
    double utcOffset, nowFrac = 0.0;

    if (loc->hasTz) {
        if (!getLocalDateAndOffset(loc->tz, &year, &month, &day, &utcOffset, &nowFrac)) {
            snprintf(result->error, sizeof(result->error),
                     "couldn't read the console's timezone data");
            return;
        }
    } else {
        utcOffset = loc->utcOffset;
        getLocalDateAndOffsetFixed(utcOffset, &year, &month, &day, &nowFrac);
    }

    PrayerCalcResult calc;
    prayerCalcCompute(loc->lat, loc->lon, utcOffset, year, month, day,
                       g_settings.method, g_settings.asrHanafi, g_settings.highLatRule, &calc);

    if (!calc.ok) {
        snprintf(result->error, sizeof(result->error), "calculation failed");
        return;
    }

    formatHourMin(calc.fajr, result->fajr, sizeof(result->fajr));
    formatHourMin(calc.sunrise, result->sunrise, sizeof(result->sunrise));
    formatHourMin(calc.dhuhr, result->dhuhr, sizeof(result->dhuhr));
    formatHourMin(calc.asr, result->asr, sizeof(result->asr));
    formatHourMin(calc.maghrib, result->maghrib, sizeof(result->maghrib));
    formatHourMin(calc.isha, result->isha, sizeof(result->isha));
    snprintf(result->dateLabel, sizeof(result->dateLabel), "%04d-%02d-%02d (Offline calculation)",
             year, month, day);
    result->ok = 1;
    result->hasCoords = 1;
    result->lat = loc->lat;
    result->lon = loc->lon;
    if (loc->hasTz) {
        result->hasTz = 1;
        snprintf(result->tz, sizeof(result->tz), "%s", loc->tz);
    } else {
        result->hasFixedOffset = 1;
        result->utcOffset = loc->utcOffset;
    }
    g_lastOfflineNowFrac = nowFrac;
}

// Preferred entry point for a CurrentLocation: tries the live Aladhan API
// first (freshest numbers), and falls back to the fully-offline calculator
// if that fails for any reason (no Wi-Fi, DNS failure, timeout, etc). A
// LOC_ADDRESS location has no offline fallback the first time it's searched
// (we don't have its coordinates until the API tells us), but once saved as
// a named location it behaves like any other.
static void getPrayerTimesForLocation(const CurrentLocation *loc, PrayerResult *result) {
    if (loc->kind == LOC_ADDRESS) {
        fetchPrayerTimesByAddress(loc->address, result);
        return;
    }

    fetchPrayerTimesByCoords(loc->label, loc->hasTz ? loc->tz : NULL, loc->lat, loc->lon, result);
    if (result->ok) {
        result->hasCoords = 1;
        result->lat = loc->lat;
        result->lon = loc->lon;
        if (loc->hasTz) { result->hasTz = 1; snprintf(result->tz, sizeof(result->tz), "%s", loc->tz); }
        else { result->hasFixedOffset = 1; result->utcOffset = loc->utcOffset; }
        return;
    }

    computeOfflineForLocation(loc, result);
    if (result->ok) {
        size_t len = strlen(result->dateLabel);
        const char *suffix = " - no internet";
        if (len + strlen(suffix) < sizeof(result->dateLabel)) {
            strcat(result->dateLabel, suffix);
        }
    }
}

static CurrentLocation locationFromCity(const CityEntry *city) {
    CurrentLocation loc;
    memset(&loc, 0, sizeof(loc));
    loc.kind = LOC_CITY;
    snprintf(loc.label, sizeof(loc.label), "%s", city->label);
    loc.hasTz = 1;
    snprintf(loc.tz, sizeof(loc.tz), "%s", city->tz);
    loc.lat = city->lat;
    loc.lon = city->lon;
    loc.hasCoords = 1;
    return loc;
}

static CurrentLocation locationFromNamed(const NamedLocation *n) {
    CurrentLocation loc;
    memset(&loc, 0, sizeof(loc));
    loc.kind = LOC_NAMED;
    snprintf(loc.label, sizeof(loc.label), "%s", n->name);
    loc.hasTz = n->hasTz;
    if (n->hasTz) snprintf(loc.tz, sizeof(loc.tz), "%s", n->tz);
    loc.utcOffset = n->utcOffset;
    loc.lat = n->lat;
    loc.lon = n->lon;
    loc.hasCoords = 1;
    return loc;
}

// ---------------------------------------------------------------------------
// Persistence -- all under sdmc:/switch/prayer-times/. Three files:
//   settings.txt   -- calc method / Asr school / high-latitude rule
//   locations.txt  -- named saved locations, one per line
//   current.txt    -- the last-used location, so we launch straight into it
// ---------------------------------------------------------------------------
#define CONFIG_DIR       "sdmc:/switch/prayer-times"
#define SETTINGS_PATH    "sdmc:/switch/prayer-times/settings.txt"
#define LOCATIONS_PATH   "sdmc:/switch/prayer-times/locations.txt"
#define CURRENT_PATH     "sdmc:/switch/prayer-times/current.txt"
#define MAX_SAVED_LOCATIONS 60

static void ensureConfigDir(void) {
    mkdir("sdmc:/switch", 0777);
    mkdir(CONFIG_DIR, 0777);
}

static void saveSettings(void) {
    ensureConfigDir();
    FILE *f = fopen(SETTINGS_PATH, "w");
    if (!f) return;
    fprintf(f, "method=%d\nasrHanafi=%d\nhighLat=%d\nshowAdvanced=%d\nuse24Hour=%d\n",
            g_settings.method, g_settings.asrHanafi, g_settings.highLatRule,
            g_settings.showAdvanced, g_settings.use24Hour);
    fclose(f);
}

static void loadSettings(void) {
    FILE *f = fopen(SETTINGS_PATH, "r");
    if (!f) return;
    char line[128];
    while (fgets(line, sizeof(line), f)) {
        char *nl = strchr(line, '\n'); if (nl) *nl = 0;
        char *eq = strchr(line, '=');
        if (!eq) continue;
        *eq = 0;
        const char *key = line;
        const char *val = eq + 1;
        if (strcmp(key, "method") == 0) g_settings.method = atoi(val);
        else if (strcmp(key, "asrHanafi") == 0) g_settings.asrHanafi = atoi(val);
        else if (strcmp(key, "highLat") == 0) g_settings.highLatRule = atoi(val);
        else if (strcmp(key, "showAdvanced") == 0) g_settings.showAdvanced = atoi(val);
        else if (strcmp(key, "use24Hour") == 0) g_settings.use24Hour = atoi(val);
    }
    fclose(f);
}

// One line per saved location, pipe-delimited:
//   name|lat|lon|hasTz|tz|utcOffset
// Names are sanitized (no '|' or newline) when saving.
static int g_savedCount = 0;
static NamedLocation g_saved[MAX_SAVED_LOCATIONS];

static void sanitizeField(char *s) {
    for (char *p = s; *p; p++) {
        if (*p == '|' || *p == '\n' || *p == '\r') *p = ' ';
    }
}

static void loadSavedLocations(void) {
    g_savedCount = 0;
    FILE *f = fopen(LOCATIONS_PATH, "r");
    if (!f) return;
    char line[512];
    while (fgets(line, sizeof(line), f) && g_savedCount < MAX_SAVED_LOCATIONS) {
        char *nl = strchr(line, '\n'); if (nl) *nl = 0;
        if (line[0] == 0) continue;
        NamedLocation n;
        memset(&n, 0, sizeof(n));
        char *tok, *save = NULL;
        int field = 0;
        tok = strtok_r(line, "|", &save);
        while (tok) {
            switch (field) {
                case 0: snprintf(n.name, sizeof(n.name), "%s", tok); break;
                case 1: n.lat = atof(tok); break;
                case 2: n.lon = atof(tok); break;
                case 3: n.hasTz = atoi(tok); break;
                case 4: snprintf(n.tz, sizeof(n.tz), "%s", tok); break;
                case 5: n.utcOffset = atof(tok); break;
            }
            field++;
            tok = strtok_r(NULL, "|", &save);
        }
        if (field >= 6) g_saved[g_savedCount++] = n;
    }
    fclose(f);
}

static void writeSavedLocations(void) {
    ensureConfigDir();
    FILE *f = fopen(LOCATIONS_PATH, "w");
    if (!f) return;
    for (int i = 0; i < g_savedCount; i++) {
        NamedLocation *n = &g_saved[i];
        fprintf(f, "%s|%f|%f|%d|%s|%f\n", n->name, n->lat, n->lon, n->hasTz,
                n->hasTz ? n->tz : "-", n->utcOffset);
    }
    fclose(f);
}

// Adds or, if a saved location with the same name exists, overwrites it.
static void addOrUpdateSavedLocation(const NamedLocation *n) {
    for (int i = 0; i < g_savedCount; i++) {
        if (strcasecmp(g_saved[i].name, n->name) == 0) {
            g_saved[i] = *n;
            writeSavedLocations();
            return;
        }
    }
    if (g_savedCount < MAX_SAVED_LOCATIONS) {
        g_saved[g_savedCount++] = *n;
        writeSavedLocations();
    }
}

static void deleteSavedLocation(int index) {
    if (index < 0 || index >= g_savedCount) return;
    for (int i = index; i < g_savedCount - 1; i++) g_saved[i] = g_saved[i + 1];
    g_savedCount--;
    writeSavedLocations();
}

// current.txt: one field per line, same shape as a NamedLocation plus kind
// and (for LOC_ADDRESS) the original search text.
static void saveCurrentLocation(const CurrentLocation *loc) {
    ensureConfigDir();
    FILE *f = fopen(CURRENT_PATH, "w");
    if (!f) return;
    fprintf(f, "kind=%d\nlabel=%s\nhasTz=%d\ntz=%s\nutcOffset=%f\nlat=%f\nlon=%f\naddress=%s\n",
            loc->kind, loc->label, loc->hasTz, loc->hasTz ? loc->tz : "-",
            loc->utcOffset, loc->lat, loc->lon,
            loc->kind == LOC_ADDRESS ? loc->address : "-");
    fclose(f);
}

static int loadCurrentLocation(CurrentLocation *out) {
    memset(out, 0, sizeof(*out));
    FILE *f = fopen(CURRENT_PATH, "r");
    if (!f) return 0;
    char line[256];
    int have = 0;
    while (fgets(line, sizeof(line), f)) {
        char *nl = strchr(line, '\n'); if (nl) *nl = 0;
        char *eq = strchr(line, '=');
        if (!eq) continue;
        *eq = 0;
        const char *key = line;
        const char *val = eq + 1;
        if (strcmp(key, "kind") == 0) { out->kind = atoi(val); have = 1; }
        else if (strcmp(key, "label") == 0) snprintf(out->label, sizeof(out->label), "%s", val);
        else if (strcmp(key, "hasTz") == 0) out->hasTz = atoi(val);
        else if (strcmp(key, "tz") == 0) snprintf(out->tz, sizeof(out->tz), "%s", val);
        else if (strcmp(key, "utcOffset") == 0) out->utcOffset = atof(val);
        else if (strcmp(key, "lat") == 0) out->lat = atof(val);
        else if (strcmp(key, "lon") == 0) out->lon = atof(val);
        else if (strcmp(key, "address") == 0) snprintf(out->address, sizeof(out->address), "%s", val);
    }
    fclose(f);
    out->hasCoords = 1;
    return have;
}

// ---------------------------------------------------------------------------
// Sorting / filtering of the offline city list.
// ---------------------------------------------------------------------------
static int compareCityLabels(const void *a, const void *b) {
    const CityEntry *ca = *(const CityEntry * const *)a;
    const CityEntry *cb = *(const CityEntry * const *)b;
    return strcasecmp(ca->label, cb->label);
}

// Case-insensitive substring search, written by hand rather than relying on
// strcasestr (not guaranteed available in the devkitPro newlib build).
static int containsCaseInsensitive(const char *haystack, const char *needle) {
    if (!*needle) return 1;
    size_t hl = strlen(haystack), nl = strlen(needle);
    for (size_t i = 0; i + nl <= hl; i++) {
        size_t j = 0;
        for (; j < nl; j++) {
            if (tolower((unsigned char)haystack[i + j]) != tolower((unsigned char)needle[j])) break;
        }
        if (j == nl) return 1;
    }
    return 0;
}

static int buildFilteredCities(const CityEntry **sortedCities, const char *filter,
                                const CityEntry **outFiltered) {
    if (!filter || !filter[0]) {
        memcpy(outFiltered, sortedCities, sizeof(CityEntry *) * CITY_COUNT);
        return CITY_COUNT;
    }
    int n = 0;
    for (int i = 0; i < CITY_COUNT; i++) {
        if (containsCaseInsensitive(sortedCities[i]->label, filter)) outFiltered[n++] = sortedCities[i];
    }
    return n;
}

// ---------------------------------------------------------------------------
// UI
// ---------------------------------------------------------------------------
#define COL_BG      "\x1b[44m"       // Standard blue background
#define COL_TEXT    "\x1b[97m"       // Bright white text
#define COL_SELECT  "\x1b[97m"       // White text (selected row)
#define COL_DIM     "\x1b[37m"       // Standard light gray text
#define COL_ACCENT  "\x1b[93m"       // Yellow -- next-prayer highlight
#define COL_RESET   "\x1b[0m"        // Reset

static void paintBackground(int *outWidth, int *outHeight) {
    PrintConsole *console = consoleGetDefault();
    int width = console->consoleWidth;
    int height = console->consoleHeight;
    if (outWidth) *outWidth = width;
    if (outHeight) *outHeight = height;

    consoleClear();
    printf("\x1b[1;1H" COL_BG COL_TEXT);
    for (int row = 0; row < height; row++) {
        for (int col = 0; col < width; col++) putchar(' ');
    }
    printf("\x1b[1;1H");
}

static void printRule(int width, char ch) {
    for (int i = 0; i < width; i++) putchar(ch);
    putchar('\n');
}

// Returns a fresh margin-padding string for the given width, written into
// pad (must be >= 64 bytes). Shared by every draw* function below.
static int computeMargins(int width, int height, int contentTargetTop, char *pad, size_t padCap) {
    int marginX = width > 70 ? (width - 66) / 2 : 2;
    int padLen = marginX < (int)padCap - 1 ? marginX : (int)padCap - 1;
    memset(pad, ' ', padLen);
    pad[padLen] = 0;
    return marginX;
}

// selected: one of SPECIAL_ENTRIES, or an index into filteredCities[0..filteredCount-1]
static void drawMenu(const CityEntry **filteredCities, int filteredCount, const char *filterText,
                      int selected, int scrollTop) {
    int width, height;
    paintBackground(&width, &height);

    char pad[64];
    int marginX = computeMargins(width, height, 0, pad, sizeof(pad));
    int marginTop = height > 38 ? (height - 34) / 2 : 1;
    for (int i = 0; i < marginTop; i++) putchar('\n');

    int contentWidth = width - marginX * 2;
    if (contentWidth < 40) contentWidth = 40;

    printf("%s", pad); printRule(contentWidth, '=');
    printf("%s   As-salamu Alaykum\n\n", pad);
    printf("%s   Please select a city, or search/enter a location\n", pad);
    printf("%s", pad); printRule(contentWidth, '=');
    printf("\n");

    const char *specialLabels[NUM_SPECIAL];
    char filterLabelBuf[80];
    if (filterText && filterText[0]) {
        snprintf(filterLabelBuf, sizeof(filterLabelBuf), "[ Filter: \"%s\" (Y to change, X to clear) ]", filterText);
    } else {
        snprintf(filterLabelBuf, sizeof(filterLabelBuf), "[ Type to filter the city list... (Y) ]");
    }
    specialLabels[0] = "[ Search for any place worldwide online... ]";
    specialLabels[1] = filterLabelBuf;
    specialLabels[2] = "[ Enter custom coordinates by hand (offline)... ]";
    specialLabels[3] = "[ My saved locations... ]";
    specialLabels[4] = "[ Settings ]";

    for (int i = 0; i < NUM_SPECIAL; i++) {
        int isSel = (selected == SPECIAL_ENTRIES[i]);
        printf("%s%s%s\n", pad, isSel ? COL_SELECT " > " COL_TEXT : "   ", specialLabels[i]);
    }
    printf("%s", pad); printRule(contentWidth, '-');

    for (int row = 0; row < VISIBLE_ROWS; row++) {
        int i = scrollTop + row;
        if (i >= filteredCount) { printf("\n"); continue; }
        int isSel = (selected >= 0 && i == selected);
        if (g_settings.showAdvanced) {
            printf("%s%s %-32s " COL_DIM "[%s]" COL_TEXT "\n",
                   pad, isSel ? COL_SELECT " > " COL_TEXT : "   ",
                   filteredCities[i]->label, filteredCities[i]->tz);
        } else {
            printf("%s%s %s\n",
                   pad, isSel ? COL_SELECT " > " COL_TEXT : "   ",
                   filteredCities[i]->label);
        }
    }

    printf("\n%s", pad);
    printRule(contentWidth, '-');

    printf("%s %d of %d offline cities shown.\n", pad, filteredCount, CITY_COUNT);
    if (g_settings.showAdvanced) {
        printf("%s Method: %s\n", pad, prayerCalcMethodName(g_settings.method));
        printf("%s Asr: %s   High-lat: %s\n", pad,
               g_settings.asrHanafi ? "Hanafi" : "Standard",
               prayerCalcHighLatName(g_settings.highLatRule));
    }
    printf("\n%s D-Pad/Stick: Move   L/R: Page   ZL/ZR: Jump letter\n", pad);
    printf("%s A: Select   Y: Filter   X: Clear filter   +: Exit\n", pad);
    printf(COL_RESET);
    consoleUpdate(NULL);
}

// Computes which prayer is next given today's six HH:MM strings and the
// current local fractional hour. Returns 1 and fills *outName/*outMinutes
// if a next prayer could be determined (i.e. we know "now" for this
// location), else 0 (shown as "--" in the UI, e.g. for a plain address
// search with no timezone info yet).
static int computeNextPrayer(const PrayerResult *r, int haveNow, double nowFrac,
                              const char **outName, int *outMinutesRemaining) {
    if (!haveNow) return 0;
    static const char *names[6] = { "Fajr", "Sunrise", "Dhuhr", "Asr", "Maghrib", "Isha" };
    const char *times[6] = { r->fajr, r->sunrise, r->dhuhr, r->asr, r->maghrib, r->isha };
    double hours[6];
    for (int i = 0; i < 6; i++) {
        if (!parseHourMin(times[i], &hours[i])) return 0;
    }
    for (int i = 0; i < 6; i++) {
        if (hours[i] > nowFrac) {
            *outName = names[i];
            *outMinutesRemaining = (int)round((hours[i] - nowFrac) * 60.0);
            return 1;
        }
    }
    // Past Isha -- next prayer is tomorrow's Fajr.
    *outName = "Fajr";
    *outMinutesRemaining = (int)round((24.0 - nowFrac + hours[0]) * 60.0);
    return 1;
}

static void drawResult(const PrayerResult *result, int haveNow, double nowFrac, int canSave) {
    int width, height;
    paintBackground(&width, &height);

    char pad[64];
    int marginX = computeMargins(width, height, 0, pad, sizeof(pad));
    int marginTop = height > 32 ? (height - 26) / 2 : 1;
    for (int i = 0; i < marginTop; i++) putchar('\n');

    int contentWidth = width - marginX * 2;
    if (contentWidth < 40) contentWidth = 40;

    printf("%s", pad); printRule(contentWidth, '=');
    printf("%s   %s\n", pad, result->placeLabel);
    if (result->dateLabel[0]) printf("%s   Date: %s\n", pad, result->dateLabel);
    printf("%s", pad); printRule(contentWidth, '=');
    printf("\n");

    if (!result->ok) {
        printf("%s   Could not fetch prayer times.\n", pad);
        printf("%s   %s\n\n", pad, result->error);
        printf("%s   Make sure the console has an active internet\n", pad);
        printf("%s   connection, or use \"Enter custom coordinates\"\n", pad);
        printf("%s   from the main menu for a fully offline lookup.\n", pad);
    } else {
        const char *nextName = NULL;
        int nextMinutes = 0;
        int haveNext = computeNextPrayer(result, haveNow, nowFrac, &nextName, &nextMinutes);

        const char *names[6] = { "Fajr", "Sunrise", "Dhuhr", "Asr", "Maghrib", "Isha" };
        const char *times[6] = { result->fajr, result->sunrise, result->dhuhr, result->asr, result->maghrib, result->isha };
        char displayTime[16];
        for (int i = 0; i < 6; i++) {
            int isNext = haveNext && strcmp(names[i], nextName) == 0;
            formatTimeDisplay(times[i], displayTime, sizeof(displayTime));
            printf("%s   %s%-9s %s\n" COL_TEXT, pad, isNext ? COL_ACCENT : COL_SELECT, names[i], displayTime);
        }

        printf("\n%s", pad); printRule(contentWidth, '-');
        if (haveNext) {
            int h = nextMinutes / 60, m = nextMinutes % 60;
            printf("%s   Next: %s in %dh %02dm\n", pad, nextName, h, m);
        } else {
            printf("%s   Next-prayer countdown unavailable for this location.\n", pad);
        }
        if (result->hasCoords) {
            double bearing = prayerCalcQiblaBearing(result->lat, result->lon);
            printf("%s   Qibla: %.0f deg (%s) from North\n", pad, bearing, compassDirection(bearing));
        }
        if (g_settings.showAdvanced) {
            printf("%s   Method: %s\n", pad, prayerCalcMethodName(g_settings.method));
            printf("%s   Asr: %s   High-lat: %s\n", pad,
                   g_settings.asrHanafi ? "Hanafi" : "Standard",
                   prayerCalcHighLatName(g_settings.highLatRule));
        }
    }

    printf("\n%s", pad); printRule(contentWidth, '-');
    printf("%s B:back  R:refresh  X:monthly  %s+:exit\n", pad,
           canSave ? "Y:save-location  " : "");
    printf(COL_RESET);
    consoleUpdate(NULL);
}

static void drawSettings(int row) {
    int width, height;
    paintBackground(&width, &height);
    char pad[64];
    int marginX = computeMargins(width, height, 0, pad, sizeof(pad));
    int marginTop = height > 30 ? (height - 20) / 2 : 1;
    for (int i = 0; i < marginTop; i++) putchar('\n');
    int contentWidth = width - marginX * 2;
    if (contentWidth < 40) contentWidth = 40;

    printf("%s", pad); printRule(contentWidth, '=');
    printf("%s   Settings\n", pad);
    printf("%s", pad); printRule(contentWidth, '=');
    printf("\n");

    printf("%s%sCalculation method:  < %s >\n" COL_TEXT, pad, row == 0 ? COL_SELECT " > " : "     ",
           prayerCalcMethodName(g_settings.method));
    printf("%s%sAsr juristic school: < %s >\n" COL_TEXT, pad, row == 1 ? COL_SELECT " > " : "     ",
           g_settings.asrHanafi ? "Hanafi" : "Standard (Shafi)");
    printf("%s%sHigh-latitude rule:  < %s >\n" COL_TEXT, pad, row == 2 ? COL_SELECT " > " : "     ",
           prayerCalcHighLatName(g_settings.highLatRule));
    printf("%s%sShow technical info: < %s >\n" COL_TEXT, pad, row == 3 ? COL_SELECT " > " : "     ",
           g_settings.showAdvanced ? "On" : "Off");
    printf("%s%sTime format:         < %s >\n" COL_TEXT, pad, row == 4 ? COL_SELECT " > " : "     ",
           g_settings.use24Hour ? "24-hour" : "12-hour (AM/PM)");

    printf("\n%s", pad); printRule(contentWidth, '-');
    printf("%s The high-latitude rule only kicks in when the plain\n", pad);
    printf("%s angle-based Fajr/Isha calculation is impossible for\n", pad);
    printf("%s the day and latitude (e.g. far north/south in summer).\n", pad);
    printf("%s \"Show technical info\" adds timezone tags to the city\n", pad);
    printf("%s list and the method/Asr/high-lat line to results.\n", pad);
    printf("\n%s", pad); printRule(contentWidth, '-');
    printf("%s Up/Down: Choose field   Left/Right: Change value   B: Save & back\n", pad);
    printf(COL_RESET);
    consoleUpdate(NULL);
}

static void drawSavedLocations(int selected, int scrollTop) {
    int width, height;
    paintBackground(&width, &height);
    char pad[64];
    int marginX = computeMargins(width, height, 0, pad, sizeof(pad));
    int marginTop = height > 34 ? (height - 30) / 2 : 1;
    for (int i = 0; i < marginTop; i++) putchar('\n');
    int contentWidth = width - marginX * 2;
    if (contentWidth < 40) contentWidth = 40;

    printf("%s", pad); printRule(contentWidth, '=');
    printf("%s   My Saved Locations (%d)\n", pad, g_savedCount);
    printf("%s", pad); printRule(contentWidth, '=');
    printf("\n");

    if (g_savedCount == 0) {
        printf("%s   No saved locations yet.\n", pad);
        printf("%s   From the results screen, press Y to save the\n", pad);
        printf("%s   location you're currently viewing.\n", pad);
    } else {
        for (int row = 0; row < VISIBLE_ROWS + 2; row++) {
            int i = scrollTop + row;
            if (i >= g_savedCount) break;
            int isSel = (i == selected);
            NamedLocation *n = &g_saved[i];
            if (g_settings.showAdvanced) {
                printf("%s%s %-28s " COL_DIM "[%s]" COL_TEXT "\n", pad,
                       isSel ? COL_SELECT " > " COL_TEXT : "   ", n->name,
                       n->hasTz ? n->tz : "fixed UTC offset");
            } else {
                printf("%s%s %s\n", pad, isSel ? COL_SELECT " > " COL_TEXT : "   ", n->name);
            }
        }
    }

    printf("\n%s", pad); printRule(contentWidth, '-');
    printf("%s A: Load   X: Delete   B: Back\n", pad);
    printf(COL_RESET);
    consoleUpdate(NULL);
}

// One row of the monthly table.
typedef struct {
    int day;
    PrayerCalcResult calc;
} MonthlyRow;

static void drawMonthly(const char *placeLabel, int year, int month, const MonthlyRow *rows, int rowCount, int scrollTop) {
    int width, height;
    paintBackground(&width, &height);
    char pad[64];
    int marginX = computeMargins(width, height, 0, pad, sizeof(pad));
    int marginTop = height > 34 ? (height - 30) / 2 : 1;
    for (int i = 0; i < marginTop; i++) putchar('\n');
    int contentWidth = width - marginX * 2;
    if (contentWidth < 40) contentWidth = 40;

    static const char *monthNames[] = { "", "January", "February", "March", "April", "May", "June",
        "July", "August", "September", "October", "November", "December" };

    printf("%s", pad); printRule(contentWidth, '=');
    printf("%s   %s -- %s %d\n", pad, placeLabel, monthNames[month], year);
    printf("%s", pad); printRule(contentWidth, '=');
    printf("\n");
    printf("%s  %-4s %-9s %-9s %-9s %-9s %-9s %-9s\n", pad,
           "Day", "Fajr", "Sunrise", "Dhuhr", "Asr", "Maghrib", "Isha");
    printf("%s", pad); printRule(contentWidth, '-');

    char fj[16], sr[16], dh[16], as[16], mg[16], is[16];
    char fjD[16], srD[16], dhD[16], asD[16], mgD[16], isD[16];
    for (int row = 0; row < VISIBLE_ROWS + 3; row++) {
        int i = scrollTop + row;
        if (i >= rowCount) break;
        const MonthlyRow *r = &rows[i];
        formatHourMin(r->calc.fajr, fj, sizeof(fj));
        formatHourMin(r->calc.sunrise, sr, sizeof(sr));
        formatHourMin(r->calc.dhuhr, dh, sizeof(dh));
        formatHourMin(r->calc.asr, as, sizeof(as));
        formatHourMin(r->calc.maghrib, mg, sizeof(mg));
        formatHourMin(r->calc.isha, is, sizeof(is));
        formatTimeDisplay(fj, fjD, sizeof(fjD));
        formatTimeDisplay(sr, srD, sizeof(srD));
        formatTimeDisplay(dh, dhD, sizeof(dhD));
        formatTimeDisplay(as, asD, sizeof(asD));
        formatTimeDisplay(mg, mgD, sizeof(mgD));
        formatTimeDisplay(is, isD, sizeof(isD));
        printf("%s  %-4d %-9s %-9s %-9s %-9s %-9s %-9s\n", pad, r->day, fjD, srD, dhD, asD, mgD, isD);
    }

    printf("\n%s", pad); printRule(contentWidth, '-');
    printf("%s Up/Down: Scroll   L/R: Prev/Next month   B: Back\n", pad);
    printf(COL_RESET);
    consoleUpdate(NULL);
}

// ---------------------------------------------------------------------------
// Custom coordinate entry flow (feature: custom coordinates)
// ---------------------------------------------------------------------------
static int promptForCustomCoordinates(CurrentLocation *out) {
    char buf[64];
    memset(out, 0, sizeof(*out));
    out->kind = LOC_CUSTOM;

    promptForText("Latitude in decimal degrees, e.g. 40.7128 or -6.2088", buf, sizeof(buf));
    if (buf[0] == 0) return 0;
    out->lat = atof(buf);

    promptForText("Longitude in decimal degrees, e.g. -74.0060 or 106.8456", buf, sizeof(buf));
    if (buf[0] == 0) return 0;
    out->lon = atof(buf);

    promptForText("UTC offset in hours for this place right now, e.g. -5 or 5.5", buf, sizeof(buf));
    if (buf[0] == 0) return 0;
    out->utcOffset = atof(buf);
    out->hasTz = 0;
    out->hasCoords = 1;
    snprintf(out->label, sizeof(out->label), "Custom (%.4f, %.4f)", out->lat, out->lon);
    return 1;
}

// Builds a NamedLocation from whatever's currently on screen and saves it,
// prompting for a name (and, if we don't already know a UTC offset for it,
// one of those too).
static void saveCurrentAsNamed(const CurrentLocation *loc, const PrayerResult *result) {
    if (!result->hasCoords && !loc->hasCoords) return;

    char name[64];
    promptForText("Name this location (e.g. \"Home\", \"Mom's House\")", name, sizeof(name));
    if (name[0] == 0) return;
    sanitizeField(name);

    NamedLocation n;
    memset(&n, 0, sizeof(n));
    snprintf(n.name, sizeof(n.name), "%s", name);
    n.lat = result->hasCoords ? result->lat : loc->lat;
    n.lon = result->hasCoords ? result->lon : loc->lon;

    if (result->hasTz) {
        n.hasTz = 1;
        snprintf(n.tz, sizeof(n.tz), "%s", result->tz);
    } else if (loc->hasTz) {
        n.hasTz = 1;
        snprintf(n.tz, sizeof(n.tz), "%s", loc->tz);
    } else if (result->hasFixedOffset) {
        n.hasTz = 0;
        n.utcOffset = result->utcOffset;
    } else if (!loc->hasTz) {
        n.hasTz = 0;
        n.utcOffset = loc->utcOffset;
        if (loc->kind == LOC_ADDRESS) {
            // Ad hoc address search with coords but no tz/offset known --
            // ask for one so the saved copy is actually usable offline.
            char buf[64];
            promptForText("UTC offset in hours for this place, e.g. -5 or 5.5", buf, sizeof(buf));
            n.utcOffset = buf[0] ? atof(buf) : 0.0;
        }
    }

    addOrUpdateSavedLocation(&n);
}

// ---------------------------------------------------------------------------
// Monthly timetable computation
// ---------------------------------------------------------------------------
static int daysInMonth(int year, int month) {
    static const int dim[] = { 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 };
    int d = dim[month - 1];
    if (month == 2) {
        int leap = (year % 4 == 0 && year % 100 != 0) || (year % 400 == 0);
        if (leap) d = 29;
    }
    return d;
}

static int buildMonthlyRows(const CurrentLocation *loc, int year, int month, MonthlyRow *rows, int maxRows) {
    if (!loc->hasCoords) return 0;
    double utcOffset = loc->hasTz ? 0.0 : loc->utcOffset;
    // For a known-timezone location, resolve a representative offset once
    // via the console's current reading (handles most DST edge cases well
    // enough for a monthly reference table; each row uses this same offset,
    // consistent with how every other offline calculator publishes a
    // monthly timetable).
    if (loc->hasTz) {
        int y, m, d; double off, now;
        if (getLocalDateAndOffset(loc->tz, &y, &m, &d, &off, &now)) utcOffset = off;
    }
    int n = daysInMonth(year, month);
    if (n > maxRows) n = maxRows;
    for (int day = 1; day <= n; day++) {
        rows[day - 1].day = day;
        prayerCalcCompute(loc->lat, loc->lon, utcOffset, year, month, day,
                           g_settings.method, g_settings.asrHanafi, g_settings.highLatRule,
                           &rows[day - 1].calc);
    }
    return n;
}

// Refreshes result/haveNow/nowFrac for currentLoc, persists it as the
// last-used location, and returns whether a next-prayer countdown is
// available for it.
static int refreshLocation(CurrentLocation *currentLoc, PrayerResult *result, double *nowFracOut) {
    getPrayerTimesForLocation(currentLoc, result);
    int haveNow = 0;
    double nowFrac = 0.0;
    if (result->ok) {
        if (result->hasTz) {
            int y, m, d; double off;
            haveNow = getLocalDateAndOffset(result->tz, &y, &m, &d, &off, &nowFrac);
        } else if (result->hasFixedOffset) {
            int y, m, d;
            getLocalDateAndOffsetFixed(result->utcOffset, &y, &m, &d, &nowFrac);
            haveNow = 1;
        } else if (currentLoc->hasTz) {
            int y, m, d; double off;
            haveNow = getLocalDateAndOffset(currentLoc->tz, &y, &m, &d, &off, &nowFrac);
        }
    }
    saveCurrentLocation(currentLoc);
    *nowFracOut = nowFrac;
    return haveNow;
}

int main(int argc, char **argv) {
    consoleInit(NULL);

    padConfigureInput(1, HidNpadStyleSet_NpadStandard);
    PadState pad;
    padInitializeDefault(&pad);

    timeInitialize();     // offline calculator's timezone/date lookups
    fsdevMountSdmc();     // settings / saved locations / last-used location

    // Network is only needed for online lookups; everything else (built-in
    // cities, custom coordinates, saved locations) works fully offline if
    // this fails to come up.
    socketInitializeDefault();
    curl_global_init(CURL_GLOBAL_DEFAULT);

    loadSettings();
    loadSavedLocations();

    const CityEntry **sortedCities = malloc(sizeof(CityEntry *) * CITY_COUNT);
    for (int i = 0; i < CITY_COUNT; i++) sortedCities[i] = &CITIES[i];
    qsort(sortedCities, CITY_COUNT, sizeof(CityEntry *), compareCityLabels);

    const CityEntry **filteredCities = malloc(sizeof(CityEntry *) * CITY_COUNT);
    int filteredCount = buildFilteredCities(sortedCities, "", filteredCities);
    char filterText[48] = { 0 };

    enum { STATE_MENU, STATE_RESULT, STATE_SETTINGS, STATE_SAVED, STATE_MONTHLY } state = STATE_MENU;
    int selected = ENTRY_SEARCH;
    int scrollTop = 0;
    int settingsRow = 0;
    int savedSelected = 0, savedScrollTop = 0;

    PrayerResult result;
    memset(&result, 0, sizeof(result));
    CurrentLocation currentLoc;
    memset(&currentLoc, 0, sizeof(currentLoc));
    int haveNow = 0;
    double nowFrac = 0.0;

    // Monthly view state.
    MonthlyRow monthlyRows[31];
    int monthlyCount = 0;
    int monthlyYear = 0, monthlyMonth = 0;
    int monthlyScrollTop = 0;

    #define REPEAT_INITIAL_DELAY 16 // frames held before repeat kicks in (~0.27s @60fps)
    #define REPEAT_INTERVAL 4       // frames between repeats once repeating (~15/sec)
    int holdDir = 0;
    int holdFrames = 0;

    // Launch straight into the last-used location, if we have one saved.
    if (loadCurrentLocation(&currentLoc)) {
        paintBackground(NULL, NULL);
        printf("\n   Loading your saved location (%s)...\n", currentLoc.label);
        consoleUpdate(NULL);
        haveNow = refreshLocation(&currentLoc, &result, &nowFrac);
        state = STATE_RESULT;
        drawResult(&result, haveNow, nowFrac, result.hasCoords || currentLoc.hasCoords);
    } else {
        drawMenu(filteredCities, filteredCount, filterText, selected, scrollTop);
    }

    while (appletMainLoop()) {
        padUpdate(&pad);
        u64 kDown = padGetButtonsDown(&pad);
        u64 kHeld = padGetButtons(&pad);

        if (kDown & HidNpadButton_Plus)
            break;

        if (state == STATE_MENU) {
            int wantDown = (kHeld & (HidNpadButton_Down | HidNpadButton_StickLDown)) != 0;
            int wantUp   = (kHeld & (HidNpadButton_Up   | HidNpadButton_StickLUp))   != 0;
            int moved = 0;
            int specialPos = -1;
            for (int i = 0; i < NUM_SPECIAL; i++) if (SPECIAL_ENTRIES[i] == selected) specialPos = i;

            if (wantDown && !wantUp) {
                if (kDown & (HidNpadButton_Down | HidNpadButton_StickLDown)) {
                    holdDir = 1; holdFrames = 0;
                    if (specialPos >= 0) {
                        if (specialPos < NUM_SPECIAL - 1) selected = SPECIAL_ENTRIES[specialPos + 1];
                        else if (filteredCount > 0) selected = 0;
                    } else if (selected < filteredCount - 1) selected++;
                    moved = 1;
                } else if (holdDir == 1) {
                    holdFrames++;
                    if (holdFrames >= REPEAT_INITIAL_DELAY && (holdFrames - REPEAT_INITIAL_DELAY) % REPEAT_INTERVAL == 0) {
                        if (specialPos < 0 && selected < filteredCount - 1) { selected++; moved = 1; }
                    }
                }
            } else if (wantUp && !wantDown) {
                if (kDown & (HidNpadButton_Up | HidNpadButton_StickLUp)) {
                    holdDir = -1; holdFrames = 0;
                    if (specialPos >= 0) {
                        if (specialPos > 0) selected = SPECIAL_ENTRIES[specialPos - 1];
                    } else if (selected == 0) {
                        selected = SPECIAL_ENTRIES[NUM_SPECIAL - 1];
                    } else selected--;
                    moved = 1;
                } else if (holdDir == -1) {
                    holdFrames++;
                    if (holdFrames >= REPEAT_INITIAL_DELAY && (holdFrames - REPEAT_INITIAL_DELAY) % REPEAT_INTERVAL == 0) {
                        if (specialPos < 0 && selected > 0) { selected--; moved = 1; }
                    }
                }
            } else {
                holdDir = 0; holdFrames = 0;
            }

            // L/R: page jump. ZL/ZR: jump to previous/next first-letter group.
            if (kDown & HidNpadButton_R) {
                if (selected < 0) { if (filteredCount > 0) selected = 0; }
                else selected = (selected + VISIBLE_ROWS < filteredCount) ? selected + VISIBLE_ROWS : filteredCount - 1;
                moved = 1;
            }
            if (kDown & HidNpadButton_L) {
                if (selected >= 0) {
                    selected = (selected - VISIBLE_ROWS >= 0) ? selected - VISIBLE_ROWS : 0;
                    moved = 1;
                }
            }
            if ((kDown & HidNpadButton_ZR) && filteredCount > 0) {
                int start = selected >= 0 ? selected : 0;
                char curLetter = tolower((unsigned char)filteredCities[start]->label[0]);
                int i = start;
                while (i < filteredCount && tolower((unsigned char)filteredCities[i]->label[0]) == curLetter) i++;
                selected = (i < filteredCount) ? i : filteredCount - 1;
                moved = 1;
            }
            if ((kDown & HidNpadButton_ZL) && filteredCount > 0) {
                int start = selected >= 0 ? selected : 0;
                if (start >= filteredCount) start = filteredCount - 1;
                char curLetter = tolower((unsigned char)filteredCities[start]->label[0]);
                int i = start;
                while (i > 0 && tolower((unsigned char)filteredCities[i]->label[0]) == curLetter) i--;
                char newLetter = tolower((unsigned char)filteredCities[i]->label[0]);
                while (i > 0 && tolower((unsigned char)filteredCities[i - 1]->label[0]) == newLetter) i--;
                selected = i;
                moved = 1;
            }

            if (moved) {
                if (selected >= 0) {
                    if (selected < scrollTop) scrollTop = selected;
                    if (selected >= scrollTop + VISIBLE_ROWS) scrollTop = selected - VISIBLE_ROWS + 1;
                } else {
                    scrollTop = 0;
                }
                drawMenu(filteredCities, filteredCount, filterText, selected, scrollTop);
            }

            if (kDown & HidNpadButton_X) {
                if (filterText[0]) {
                    filterText[0] = 0;
                    filteredCount = buildFilteredCities(sortedCities, filterText, filteredCities);
                    selected = ENTRY_SEARCH;
                    scrollTop = 0;
                    drawMenu(filteredCities, filteredCount, filterText, selected, scrollTop);
                }
            }

            if (kDown & HidNpadButton_A) {
                if (selected == ENTRY_SEARCH) {
                    char query[100];
                    promptForText("Enter a place (e.g. Jersey City, United States)", query, sizeof(query));
                    if (query[0] != 0) {
                        memset(&currentLoc, 0, sizeof(currentLoc));
                        currentLoc.kind = LOC_ADDRESS;
                        snprintf(currentLoc.label, sizeof(currentLoc.label), "%s", query);
                        snprintf(currentLoc.address, sizeof(currentLoc.address), "%s", query);
                        paintBackground(NULL, NULL);
                        printf("\n   Searching for \"%s\"...\n", query);
                        consoleUpdate(NULL);
                        haveNow = refreshLocation(&currentLoc, &result, &nowFrac);
                        state = STATE_RESULT;
                        drawResult(&result, haveNow, nowFrac, result.hasCoords || currentLoc.hasCoords);
                    } else {
                        drawMenu(filteredCities, filteredCount, filterText, selected, scrollTop);
                    }
                } else if (selected == ENTRY_FILTER) {
                    promptForText("Filter cities by name/country (blank clears)", filterText, sizeof(filterText));
                    filteredCount = buildFilteredCities(sortedCities, filterText, filteredCities);
                    selected = filteredCount > 0 ? 0 : ENTRY_SEARCH;
                    scrollTop = 0;
                    drawMenu(filteredCities, filteredCount, filterText, selected, scrollTop);
                } else if (selected == ENTRY_CUSTOM) {
                    CurrentLocation loc;
                    if (promptForCustomCoordinates(&loc)) {
                        currentLoc = loc;
                        paintBackground(NULL, NULL);
                        printf("\n   Computing prayer times for your coordinates...\n");
                        consoleUpdate(NULL);
                        haveNow = refreshLocation(&currentLoc, &result, &nowFrac);
                        state = STATE_RESULT;
                        drawResult(&result, haveNow, nowFrac, result.hasCoords || currentLoc.hasCoords);
                    } else {
                        drawMenu(filteredCities, filteredCount, filterText, selected, scrollTop);
                    }
                } else if (selected == ENTRY_SAVED) {
                    savedSelected = 0; savedScrollTop = 0;
                    state = STATE_SAVED;
                    drawSavedLocations(savedSelected, savedScrollTop);
                } else if (selected == ENTRY_SETTINGS) {
                    settingsRow = 0;
                    state = STATE_SETTINGS;
                    drawSettings(settingsRow);
                } else {
                    const CityEntry *city = filteredCities[selected];
                    currentLoc = locationFromCity(city);
                    paintBackground(NULL, NULL);
                    printf("\n   Fetching prayer times for %s...\n", city->label);
                    consoleUpdate(NULL);
                    haveNow = refreshLocation(&currentLoc, &result, &nowFrac);
                    state = STATE_RESULT;
                    drawResult(&result, haveNow, nowFrac, result.hasCoords || currentLoc.hasCoords);
                }
            } else if (kDown & HidNpadButton_Y) {
                promptForText("Filter cities by name/country (blank clears)", filterText, sizeof(filterText));
                filteredCount = buildFilteredCities(sortedCities, filterText, filteredCities);
                selected = filteredCount > 0 ? 0 : ENTRY_SEARCH;
                scrollTop = 0;
                drawMenu(filteredCities, filteredCount, filterText, selected, scrollTop);
            }
        } else if (state == STATE_RESULT) {
            if (kDown & HidNpadButton_B) {
                state = STATE_MENU;
                drawMenu(filteredCities, filteredCount, filterText, selected, scrollTop);
            } else if (kDown & HidNpadButton_R) {
                paintBackground(NULL, NULL);
                printf("\n   Refreshing...\n");
                consoleUpdate(NULL);
                haveNow = refreshLocation(&currentLoc, &result, &nowFrac);
                drawResult(&result, haveNow, nowFrac, result.hasCoords || currentLoc.hasCoords);
            } else if (kDown & HidNpadButton_Y) {
                if (result.hasCoords || currentLoc.hasCoords) {
                    saveCurrentAsNamed(&currentLoc, &result);
                    drawResult(&result, haveNow, nowFrac, 1);
                }
            } else if (kDown & HidNpadButton_X) {
                if (currentLoc.hasCoords || result.hasCoords) {
                    // Prefer whatever coordinates/timezone the result
                    // actually used (may differ slightly from currentLoc
                    // for an address search resolved by the API).
                    CurrentLocation monthLoc = currentLoc;
                    if (result.hasCoords) { monthLoc.lat = result.lat; monthLoc.lon = result.lon; monthLoc.hasCoords = 1; }
                    if (result.hasTz) { monthLoc.hasTz = 1; snprintf(monthLoc.tz, sizeof(monthLoc.tz), "%s", result.tz); }
                    else if (result.hasFixedOffset) { monthLoc.hasTz = 0; monthLoc.utcOffset = result.utcOffset; }

                    int y, m, d; double off, now;
                    if (monthLoc.hasTz && getLocalDateAndOffset(monthLoc.tz, &y, &m, &d, &off, &now)) {
                        monthlyYear = y; monthlyMonth = m;
                    } else if (!monthLoc.hasTz) {
                        getLocalDateAndOffsetFixed(monthLoc.utcOffset, &y, &m, &d, &now);
                        monthlyYear = y; monthlyMonth = m;
                    } else {
                        monthlyYear = 2026; monthlyMonth = 1; // shouldn't normally happen
                    }
                    monthlyCount = buildMonthlyRows(&monthLoc, monthlyYear, monthlyMonth, monthlyRows, 31);
                    monthlyScrollTop = 0;
                    currentLoc = monthLoc;
                    state = STATE_MONTHLY;
                    drawMonthly(result.placeLabel, monthlyYear, monthlyMonth, monthlyRows, monthlyCount, monthlyScrollTop);
                }
            }
        } else if (state == STATE_SETTINGS) {
            int changed = 0;
            if (kDown & (HidNpadButton_Down | HidNpadButton_StickLDown)) { settingsRow = (settingsRow + 1) % 5; changed = 1; }
            if (kDown & (HidNpadButton_Up | HidNpadButton_StickLUp)) { settingsRow = (settingsRow + 4) % 5; changed = 1; }
            if (kDown & (HidNpadButton_Right | HidNpadButton_StickLRight | HidNpadButton_A)) {
                if (settingsRow == 0) {
                    int idx = indexOfInt(METHOD_CHOICES, NUM_METHOD_CHOICES, g_settings.method);
                    g_settings.method = METHOD_CHOICES[(idx + 1) % NUM_METHOD_CHOICES];
                } else if (settingsRow == 1) {
                    g_settings.asrHanafi = !g_settings.asrHanafi;
                } else if (settingsRow == 2) {
                    int idx = indexOfInt(HIGHLAT_CHOICES, NUM_HIGHLAT_CHOICES, g_settings.highLatRule);
                    g_settings.highLatRule = HIGHLAT_CHOICES[(idx + 1) % NUM_HIGHLAT_CHOICES];
                } else if (settingsRow == 3) {
                    g_settings.showAdvanced = !g_settings.showAdvanced;
                } else {
                    g_settings.use24Hour = !g_settings.use24Hour;
                }
                changed = 1;
            }
            if (kDown & (HidNpadButton_Left | HidNpadButton_StickLLeft)) {
                if (settingsRow == 0) {
                    int idx = indexOfInt(METHOD_CHOICES, NUM_METHOD_CHOICES, g_settings.method);
                    g_settings.method = METHOD_CHOICES[(idx - 1 + NUM_METHOD_CHOICES) % NUM_METHOD_CHOICES];
                } else if (settingsRow == 1) {
                    g_settings.asrHanafi = !g_settings.asrHanafi;
                } else if (settingsRow == 2) {
                    int idx = indexOfInt(HIGHLAT_CHOICES, NUM_HIGHLAT_CHOICES, g_settings.highLatRule);
                    g_settings.highLatRule = HIGHLAT_CHOICES[(idx - 1 + NUM_HIGHLAT_CHOICES) % NUM_HIGHLAT_CHOICES];
                } else if (settingsRow == 3) {
                    g_settings.showAdvanced = !g_settings.showAdvanced;
                } else {
                    g_settings.use24Hour = !g_settings.use24Hour;
                }
                changed = 1;
            }
            if (changed) drawSettings(settingsRow);

            if (kDown & HidNpadButton_B) {
                saveSettings();
                state = STATE_MENU;
                if (currentLoc.hasCoords) {
                    // Recompute so the results screen reflects the new
                    // settings immediately if the person goes back to it.
                    haveNow = refreshLocation(&currentLoc, &result, &nowFrac);
                }
                drawMenu(filteredCities, filteredCount, filterText, selected, scrollTop);
            }
        } else if (state == STATE_SAVED) {
            int moved = 0;
            if ((kDown & (HidNpadButton_Down | HidNpadButton_StickLDown)) && savedSelected < g_savedCount - 1) { savedSelected++; moved = 1; }
            if ((kDown & (HidNpadButton_Up | HidNpadButton_StickLUp)) && savedSelected > 0) { savedSelected--; moved = 1; }
            if (moved) {
                if (savedSelected < savedScrollTop) savedScrollTop = savedSelected;
                if (savedSelected >= savedScrollTop + VISIBLE_ROWS + 2) savedScrollTop = savedSelected - VISIBLE_ROWS - 1;
                drawSavedLocations(savedSelected, savedScrollTop);
            }
            if ((kDown & HidNpadButton_A) && g_savedCount > 0) {
                currentLoc = locationFromNamed(&g_saved[savedSelected]);
                paintBackground(NULL, NULL);
                printf("\n   Loading %s...\n", currentLoc.label);
                consoleUpdate(NULL);
                haveNow = refreshLocation(&currentLoc, &result, &nowFrac);
                state = STATE_RESULT;
                drawResult(&result, haveNow, nowFrac, result.hasCoords || currentLoc.hasCoords);
            } else if ((kDown & HidNpadButton_X) && g_savedCount > 0) {
                deleteSavedLocation(savedSelected);
                if (savedSelected >= g_savedCount) savedSelected = g_savedCount - 1;
                if (savedSelected < 0) savedSelected = 0;
                drawSavedLocations(savedSelected, savedScrollTop);
            } else if (kDown & HidNpadButton_B) {
                state = STATE_MENU;
                drawMenu(filteredCities, filteredCount, filterText, selected, scrollTop);
            }
        } else { // STATE_MONTHLY
            int moved = 0;
            int maxScroll = monthlyCount - (VISIBLE_ROWS + 3);
            if (maxScroll < 0) maxScroll = 0;
            if ((kDown & (HidNpadButton_Down | HidNpadButton_StickLDown)) && monthlyScrollTop < maxScroll) { monthlyScrollTop++; moved = 1; }
            if ((kDown & (HidNpadButton_Up | HidNpadButton_StickLUp)) && monthlyScrollTop > 0) { monthlyScrollTop--; moved = 1; }
            if (kDown & (HidNpadButton_R | HidNpadButton_L)) {
                int dir = (kDown & HidNpadButton_R) ? 1 : -1;
                monthlyMonth += dir;
                if (monthlyMonth > 12) { monthlyMonth = 1; monthlyYear++; }
                if (monthlyMonth < 1) { monthlyMonth = 12; monthlyYear--; }
                monthlyCount = buildMonthlyRows(&currentLoc, monthlyYear, monthlyMonth, monthlyRows, 31);
                monthlyScrollTop = 0;
                moved = 1;
            }
            if (moved) drawMonthly(result.placeLabel, monthlyYear, monthlyMonth, monthlyRows, monthlyCount, monthlyScrollTop);
            if (kDown & HidNpadButton_B) {
                state = STATE_RESULT;
                drawResult(&result, haveNow, nowFrac, result.hasCoords || currentLoc.hasCoords);
            }
        }

        consoleUpdate(NULL);
    }

    free(sortedCities);
    free(filteredCities);
    curl_global_cleanup();
    socketExit();
    fsdevUnmountAll();
    timeExit();
    consoleExit(NULL);
    return 0;
}
